version: '3.8'
name: onxgraph-test
services:
  mongodb:
    container_name: mongo-test
    image: mongo:latest
    ports:
      - '2998:27017'
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=testAdmin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=onxGraphTest
  server:
    depends_on:
      - mongodb
    container_name: server-api-test
    image: stevanfreeborn/onx-graph-server:${SERVER_VERSION}
    ports:
      - '3000:8080'
    restart: unless-stopped
    environment:
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
      - AllowedHosts=*
      - JwtOptions__Secret=qqs+CKdh2KQOoXS4asnTaIdu+/DFnfsMIh10u1ODG1Q=
      - JwtOptions__Issuer=TestIssuer
      - JwtOptions__Audience=TestAudience
      - JwtOptions__ExpiryInMinutes=5
      - MongoDbOptions__ConnectionString=mongodb://testAdmin:password@mongodb:27017/onxGraphTest?authMechanism=SCRAM-SHA-256&authSource=admin&retryWrites=true&w=majority
      - MongoDbOptions__DatabaseName=onxGraphTest
      - CorsOptions__AllowedOrigins__0=http://localhost:3001
      - CorsOptions__AllowedOrigins__1=https://localhost:3001
  client:
    container_name: vue-client-test
    image: stevanfreeborn/onx-graph-client:${CLIENT_VERSION}
    ports:
      - '3001:80'
    restart: unless-stopped
