version: '3.8'
services:
  client:
    container_name: vue-client-production
    build:
      target: production-stage
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3001:80'
    restart: unless-stopped
