name: Pull Request - Client Changes
defaults:
  run:
    working-directory: ./client
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'client/**'
      - '!nginx/**'
      - '!public/**'
      - '!.env.vault'
      - '!.eslintrc.cjs'
      - '!.gitignore'
      - '!.prettierrc.json'
      - '!README.md'
    branches:
      - main
jobs:
  vitest_tests:
    name: Run vitest tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test:unit:coverage
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: vitest-coverage
          path: ./client/tests/coverage
  playwright_tests:
    name: Run playwright tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install dependencies
        run: npm install
      - name: Install playwright dependencies
        run: npx playwright install
      - name: Run tests
        run: npm run test:e2e
      - name: Upload e2e test results
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: ./client/playwright-report