name: Pull Request - Server Changes
env:
  JwtOptions__Secret: qqs+CKdh2KQOoXS4asnTaIdu+/DFnfsMIh10u1ODG1Q= # This is not a real secret.
  JwtOptions__Issuer: TestIssuer
  JwtOptions__Audience: TestAudience
  JwtOptions__ExpiryInMinutes: 5
defaults:
  run:
    working-directory: ./server
on:
  workflow_dispatch:
  pull_request:
    paths:
      - server/Server.API/**
      - server/Server.API.Tests/**
    branches:
      - main
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x.x
      - name: Install report generator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool --version 5.2.0
      - name: Restore dependencies
        run: dotnet restore
      - name: Build project
        run: dotnet build --no-restore
      - name: Test project
        run: dotnet test -e DOTNET_ENVIRONMENT=CI --no-build --verbosity normal
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./server/Server.API.Tests/TestResults
